// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"MAXPUMP1/pkg/api/handlers"
	"MAXPUMP1/pkg/db"
	"MAXPUMP1/pkg/repository"
	"MAXPUMP1/pkg/usecase"
)

// Injectors from wire.go:

func InitializeApi() *handlers.UserHandler {
	gormDB := db.ConnectDB()
	userInterface := repository.NewUserRepository(gormDB)
	userUsecaseInterface := usecase.NewUser(userInterface)
	userHandler := handlers.NewUserHandler(userUsecaseInterface)
	return userHandler
}
